### ISSUE TITLE
Testing with Postman Failing and C# Examples Failing 

### ISSUE THREAD

**Issue by gwsampso** [BurtonR/sqlrest#9]
I've successfully used your docker image **burtonr/sqlrest:0.2** to `/ping` and too `/connect`

I'm now trying to `/v1/procedure` with postman and also within your C# example.

In postman I constantly return the response `"message": "Handling the PROCEDURE"`

I believe I'm successfully creating the authorization header

**Postman Pre-request Script** 

        var crypto = require('crypto-js'); 
        
        const key = "sqlrestTestKey";
        
        var body = pm.request.body.toString(); 
        
        function createHmac(message) {
            var hmac = crypto.HmacSHA256(message,key)
            return hmac
        }
        
        function setAuthHeader(message) {
            const realm = "testing-func"
            let hmac = ''
            if (message) {
                hmac = createHmac(message)
            }
            const nonce = crypto.lib.WordArray.random(16)
            const timestamp = new Date().getTime()
            pm.environment.set("timestamp", timestamp);
            const authHeader = `${realm}:${hmac}:${nonce}:${timestamp}`
        
            return authHeader
        }
        
        my_auth_header = setAuthHeader(body)
        
        pm.environment.set("Authorization",my_auth_header)

Is the docker image up to date because I also had poor results when testing your C# examples

 `dotnet run procedure` 
Error Happened!
Handling the PROCEDURE

 `dotnet run query` 
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by gwsampso** [comment]
![image](https://user-images.githubusercontent.com/19770122/65217283-f0e72180-daf6-11e9-90a6-6eb613863f64.png)

**Comment by burtonr** [comment]
Hey @gwsampso Thanks for trying this project out.

It seems that the auto-build from Docker had broke some time ago, and I was not aware. The delete and procedure endpoints were implemented _after_ the 0.2 image.

I've just manually created the `burtonr/sqlrest:03`image and pushed it to Docker Hub. Please update your image and try it again.

Do let me know if you're still having troubles with it

**Comment by gwsampso** [comment]
Thanks @burtonr I thought something didn't look right. Thanks greatly for updating the build.

    docker pull burtonr/sqlrest:0.3
    docker run -d -p 5050:5050 -e DATABASE_USERNAME=username-e DATABASE_PASSWORD=password -e DATABASE_SERVER=ipaddress -e SQLREST_ALLOWED_REALMS=test-func,qa-func -e SQLREST_API_KEY=sqlrestTestKey --name sqlrest burtonr/sqlrest:0.3


### TESTING

**Test**: `/ping` 
**Result**: FAIL
**Error**: HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

**Test**: `/connect` 
**Result**: FAIL
**Error**: HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

Similarly `v1/query` and `v1/procedure` fail

Could you please look into when you get the chance, I'm going to have a crack today at debugging but not 100% sure where to start.

Reason: We were hoping to maybe utilize this with openfaas.

Thanks

**Comment by gwsampso** [comment]
Sorry it is working now with the updated C# example - thanks

I will have to work on my postman effort to add the authorization headers which look to be required for all endpoints now, which is totally fine

There are small changes required to the main readme.md to bring inline with the examples

**Comment by burtonr** [comment]
Hey @gwsampso Glad it's working for you! Please let me know if you run in to any other issues, or think of something that could be added
